FROM python:3.10-alpine

WORKDIR /app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8082

CMD ["python", "src/server.py"]

#docker build -t bekinggo/ubicaciones .
#docker push bekinggo/ubicaciones