FROM python:3.10-alpine

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "src/cronjob.py"]

#docker build --platform=linux/amd64 -t us-central1-docker.pkg.dev/forward-fuze-456010-c2/sa-p7/cronjob:latest .
#docker push us-central1-docker.pkg.dev/forward-fuze-456010-c2/sa-p7/cronjob:latest