FROM python:3.10-alpine

WORKDIR /app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8082

CMD ["python", "src/server.py"]

#docker build --platform=linux/amd64 -t us-central1-docker.pkg.dev/awesome-icon-454901-t8/sa-p6/ubicaciones:latest .
#docker push us-central1-docker.pkg.dev/awesome-icon-454901-t8/sa-p6/ubicaciones:latest