
CREATE DATABASE IF NOT EXISTS practica2;

USE practica2;

-- Table for user data
CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user VARCHAR(255) NOT NULL UNIQUE,
    pass VARCHAR(255) NOT NULL
);
