FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY . .

FROM node:20-alpine
WORKDIR /app

COPY --from=builder /app /app

EXPOSE 8080

CMD ["node", "src/server.js"]

#docker build -t bekinggo/api-gateway .
#docker push bekinggo/api-gateway