FROM python:3.10-alpine

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8081

CMD ["python", "src/server.py"]

#docker build -t bekinggo/equipos .
#docker push bekinggo/equipos

#docker network create my-network
#docker run --name mysql-container --network my-network -e MYSQL_ROOT_PASSWORD=1234 -p 3307:3306 -d mysql:latest
#docker run --name equipos-app --network my-network -e DB_HOST=mysql-container -e DB_USER=root -e DB_PASSWORD=1234 -e DB_NAME=equipos_db -e DB_PORT=3306 -p 8081:8081 -d bekinggo/equipos



