FROM python:3.10-alpine

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8081

CMD ["python", "src/server.py"]

#docker build -t bekinggo/equipos .
#docker push bekinggo/equipos

#docker network create my-network
#docker run --name mysql-container --network my-network -e MYSQL_ROOT_PASSWORD=1234 -p 3306:3306 -d mysql:latest
#docker run --name express-app --network my-network -p 8081:8081 -d bekinggo/equipos

