apiVersion: apps/v1
kind: Deployment
metadata:
  name: equipos
  namespace: sa-p8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: equipos
  template:
    metadata:
      labels:
        app: equipos
    spec:
      containers:
      - name: equipos
        image: us-central1-docker.pkg.dev/forward-fuze-456010-c2/sa-p8/equipos:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
            
        ports:
        - containerPort: 8081
        env:
        - name: DB_HOST
          value: "sa-202006353-practicas.c7qcsa8iso3p.us-east-2.rds.amazonaws.com"
        - name: DB_USER
          value: "whyrds"
        - name: DB_PASSWORD
          value: "KilW6kS53ukPsX2OaGfQ"
        - name: DB_NAME
          value: "equipos_db"
        - name: DB_PORT
          value: "3306"

---
apiVersion: v1
kind: Service
metadata:
  name: equipos
  namespace: sa-p8
spec:
  selector:
    app: equipos
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: equipos-autoscaler
  namespace: sa-p8
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: equipos
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80