FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install 

COPY . .

EXPOSE 8084

CMD [ "node", "src/server.js" ]

#docker build -t bekinggo/reportes .
#docker push bekinggo/reportes

#docker network create my-network
#docker run --name mysql-container --network my-network -e MYSQL_ROOT_PASSWORD=1234 -p 3306:3306 -d mysql:latest
#docker run --name express-app --network my-network -p 8084:8084 -d bekinggo/reportes