FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY . .

FROM node:20-alpine
WORKDIR /app

COPY --from=builder /app /app

EXPOSE 8083

CMD ["node", "src/server.js"]

#docker build --platform=linux/amd64 -t us-central1-docker.pkg.dev/hallowed-key-458002-a1/sa-p9/mantenimiento:latest .
#docker push us-central1-docker.pkg.dev/hallowed-key-458002-a1/sa-p9/mantenimiento:latest