clusterName: "elasticsearch"

nodeGroup: "master" 

replicas: 1
minimumMasterNodes: 1

resources:
  requests:
    cpu:    "250m"
    memory: "2Gi"
  limits:
    cpu:    "500m"
    memory: "4Gi"

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi

persistence:
  enabled: true

testFramework:
  enabled: false

updateStrategy: OnDelete 