apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: sa-p8
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.5.1
          resources:
            requests:
              cpu:    "250m"
              memory: "1Gi"
            limits:
              cpu:    "500m"
              memory: "2Gi"
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch-master:9200"
            - name: ELASTICSEARCH_SERVICEACCOUNT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kibana-system-token
                  key: token
          ports:
            - containerPort: 5601

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: sa-p8
spec:
  type: ClusterIP
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
      protocol: TCP
      name: http
