FROM python:3.10-alpine

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8082

CMD ["python", "-m", "src.server"]

#docker build --platform=linux/amd64 -t us-central1-docker.pkg.dev/forward-fuze-456010-c2/sa-p7/ubicaciones:latest .
#docker push us-central1-docker.pkg.dev/forward-fuze-456010-c2/sa-p7/ubicaciones:latest