apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
  namespace: sa-p9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: us-central1-docker.pkg.dev/hallowed-key-458002-a1/sa-p9/chatbot:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8085
        env:
        - name: BASE_URL_EQUIPOS
          value: "http://34.28.230.28"
        - name: BASE_URL_UBICACIONES
          value: "http://34.28.230.28"
        - name: BASE_URL_MANTENIMIENTO
          value: "http://34.28.230.28/mantenimiento/"
        - name: BASE_URL_REPORTES
          value: "http://34.28.230.28/reportes/"

---
apiVersion: v1
kind: Service
metadata:
  name: chatbot
  namespace: sa-p9
spec:
  selector:
    app: chatbot
  ports:
  - port: 8085
    targetPort: 8085
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: chatbot-autoscaler
  namespace: sa-p9
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chatbot
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80