apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubicaciones
  namespace: sa-p9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubicaciones
  template:
    metadata:
      labels:
        app: ubicaciones
    spec:
      containers:
      - name: ubicaciones
        image: us-central1-docker.pkg.dev/hallowed-key-458002-a1/sa-p9/ubicaciones:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
            
        ports:
        - containerPort: 8082
        env:
        - name: DB_HOST
          value: "sa-202006353-prod.cne0mki8e4wp.us-east-2.rds.amazonaws.com"
        - name: DB_USER
          value: "whyrds"
        - name: DB_PASSWORD
          value: "v7lnUneF9cSVSSmdFMiv"
        - name: DB_NAME
          value: "ubicaciones_db"
        - name: DB_PORT
          value: "3306"

---
apiVersion: v1
kind: Service
metadata:
  name: ubicaciones
  namespace: sa-p9
spec:
  selector:
    app: ubicaciones
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ubicaciones-autoscaler
  namespace: sa-p9
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ubicaciones
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80