apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: sa-p5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: bekinggo/api-gateway
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: MS_EQUIPOS
          value: "http://equipos.sa-p5.svc.cluster.local:8081"
        - name: MS_UBICACIONES
          value: "http://ubicaciones.sa-p5.svc.cluster.local:8082"
        - name: MS_MANTENIMIENTO
          value: "http://mantenimiento.sa-p5.svc.cluster.local:8083"
        - name: MS_REPORTES
          value: "http://reportes.sa-p5.svc.cluster.local:8084"

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: sa-p5
spec:
  selector:
    app: api-gateway
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31080
  type: NodePort

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-autoscaler
  namespace: sa-p5
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80