apiVersion: apps/v1
kind: Deployment
metadata:
  name: equipos
  namespace: sa-p5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: equipos
  template:
    metadata:
      labels:
        app: equipos
    spec:
      containers:
      - name: equipos
        image: bekinggo/equipos
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "1234"
        - name: DB_NAME
          value: "equipos_db"
        - name: DB_PORT
          value: "3306"

---
apiVersion: v1
kind: Service
metadata:
  name: equipos
  namespace: sa-p5
spec:
  selector:
    app: equipos
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: equipos-autoscaler
  namespace: sa-p5
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: equipos
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80