apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportes
  namespace: sa-p6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reportes
  template:
    metadata:
      labels:
        app: reportes
    spec:
      containers:
      - name: reportes
        image: us-central1-docker.pkg.dev/awesome-icon-454901-t8/sa-p6/reportes:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8084
        env:
        - name: DB_HOST
          value: "database-1.c7qcsa8iso3p.us-east-2.rds.amazonaws.com"
        - name: DB_USER
          value: "whyrds"
        - name: DB_PASSWORD
          value: "KCKHEVGrkDddwBhQWrG9"
        - name: DB_NAME
          value: "reportes_db"
        - name: DB_PORT
          value: "3306"

---
apiVersion: v1
kind: Service
metadata:
  name: reportes
  namespace: sa-p6
spec:
  selector:
    app: reportes
  ports:
  - port: 8084
    targetPort: 8084
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reportes-autoscaler
  namespace: sa-p6
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reportes
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
