apiVersion: monitoring.googleapis.com/v1
kind: Rules
metadata:
  name: default-alerts
  namespace: sa-p8
spec:
  groups:
  - name: resource-alerts
    interval: 1m
    rules:
    - alert: HighPodCPU
      expr: rate(container_cpu_usage_seconds_total{namespace="sa-p8",container!="POD"}[5m]) * 100 > 80
      for: 3m
      labels:
        severity: warning
      annotations:
        summary: "CPU > 80% en {{ $labels.pod }}"
    - alert: HighPodMemory
      expr: container_memory_working_set_bytes{namespace="sa-p8",container!="POD"} / 1024 / 1024 > 128
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Memoria > 128MiB en {{ $labels.pod }}"
  