FROM python:3.10-alpine

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "src/cronjob.py"]

#docker build --platform=linux/amd64 -t us-central1-docker.pkg.dev/awesome-icon-454901-t8/sa-p6/cronjob:latest .
#docker push us-central1-docker.pkg.dev/awesome-icon-454901-t8/sa-p6/cronjob:latest