replicas: 1

image: "docker.elastic.co/logstash/logstash"
imageTag: "8.6.2"
imagePullPolicy: "IfNotPresent"

service:
  type: ClusterIP
  ports:
    - name: beats
      port: 5044
      protocol: TCP
      targetPort: 5044
    - name: http
      port: 9600
      protocol: TCP
      targetPort: http

httpPort: 9600

extraPorts:
  - name: beats
    containerPort: 5044

logstashConfig:
  logstash.yml: |
    http.host: 0.0.0.0
    xpack.monitoring.enabled: false

logstashPipeline:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    filter {
      # tus filtros aquí
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-master:9200"]
        index => "logs-%{+YYYY.MM.dd}"
      }
    }

persistence:
  enabled: true

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi

resources:
  requests:
    cpu:    "250m"
    memory: "512Mi"
  limits:
    cpu:    "500m"
    memory: "1Gi"

updateStrategy: OnDelete
